schema = 3

[mod]
  [mod."filippo.io/edwards25519"]
    version = "v1.1.0"
    hash = "sha256-9ACANrgWZSd5HYPfDZHY8DVbPSC9LOMgy8deq3rDOoc="
  [mod."github.com/AndreasBriese/bbloom"]
    version = "v0.0.0-20190825152654-46b345b51c96"
    hash = "sha256-ydIJ4QKvQsDSAook9y0doDaTeXpyQUy1T+ySfOgFLAg="
  [mod."github.com/BurntSushi/toml"]
    version = "v1.3.2"
    hash = "sha256-FIwyH67KryRWI9Bk4R8s1zFP0IgKR4L66wNQJYQZLeg="
  [mod."github.com/Masterminds/goutils"]
    version = "v1.1.1"
    hash = "sha256-MEvA5e099GUllILa5EXxa6toQexU1sz6eDZt2tiqpCY="
  [mod."github.com/Masterminds/semver/v3"]
    version = "v3.2.1"
    hash = "sha256-VKHIquwriyOL8A0qgtmap/3cGEOpDokOLtPg1w4xjMA="
  [mod."github.com/Masterminds/sprig/v3"]
    version = "v3.2.3"
    hash = "sha256-1GLZic3WQIBZGyjvyHbfcZ/7EV7oNzNhkwEiiTpVfL4="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.6.1"
    hash = "sha256-BL0BVaHtmPKQts/711W59AbHXjGKqFS4ZTal0RYnR9I="
  [mod."github.com/alecthomas/chroma/v2"]
    version = "v2.13.0"
    hash = "sha256-fYwAHQFWGWzcMO8XPNzR7iAUarVGMKJjfX1DB74AmrA="
  [mod."github.com/antlr4-go/antlr/v4"]
    version = "v4.13.0"
    hash = "sha256-98nKVlsgv1S7vMvGuKOQINOKkiEvrlX5DCSmyr6Mr+A="
  [mod."github.com/aryann/difflib"]
    version = "v0.0.0-20210328193216-ff5ff6dc229b"
    hash = "sha256-QaGcdek1bA6eekbxVTDaidFZrWeGk+of35NTV94lVXw="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/caddyserver/caddy/v2"]
    version = "v2.7.6"
    hash = "sha256-9teEdXArE1d/H4HYEEBUlI2eCSjSJnitMR+S9vmT4zE="
  [mod."github.com/caddyserver/certmagic"]
    version = "v0.20.0"
    hash = "sha256-jWizMptX2/wuYPZwnjK9ffCv5/prVMH6EWi6IkdQsEA="
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.3.0"
    hash = "sha256-wfVjNZsGG1WoNC5aL+kdcy6QXPgZo4THAevZ1787md8="
  [mod."github.com/cespare/xxhash"]
    version = "v1.1.0"
    hash = "sha256-nVDTtXH9PC3yJ0THaQZEN243UP9xgLi/clt5xRqj3+M="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/chzyer/readline"]
    version = "v1.5.1"
    hash = "sha256-6wKd6/JZ9/O7FwSyNKE3KOt8fVPZEunqbTHQUxlOUNc="
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.4"
    hash = "sha256-pQ+H8Psh92KWTang8hK0cHFLomH+4X0rMMilIJUQ4Qc="
  [mod."github.com/dgraph-io/badger"]
    version = "v1.6.2"
    hash = "sha256-D/iXyiNZ8/7tBtA9msk10vVWfohWEPqFdobzRwKlvQQ="
  [mod."github.com/dgraph-io/badger/v2"]
    version = "v2.2007.4"
    hash = "sha256-+KwqZJZpViv8S3TqUVvPXrFoMgWFyS3NoLsi4RR5fGk="
  [mod."github.com/dgraph-io/ristretto"]
    version = "v0.1.1"
    hash = "sha256-Wr9ovXhGi71+n37EnrpIj2o9goyaQHtY4Vvurv6IVlY="
  [mod."github.com/dgryski/go-farm"]
    version = "v0.0.0-20200201041132-a6ae2369ad13"
    hash = "sha256-aOMlPwFY36bLiiIx4HonbCYRAhagk5N6HAWN7Ygif+E="
  [mod."github.com/dlclark/regexp2"]
    version = "v1.11.0"
    hash = "sha256-iXBBgykYu9Dcd+7LMJyRYc3Ry47jmuLGZFW13zU6toU="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/fxamacker/cbor/v2"]
    version = "v2.6.0"
    hash = "sha256-8EMjmc2FYVb0OXuzU1FWkSqYEtJjYdIT2PWsChoiTyQ="
  [mod."github.com/go-chi/chi/v5"]
    version = "v5.0.12"
    hash = "sha256-PhCb3wVSzuIXxZxM7aB3MdMLK3nnvUMhaMXk+p+H6Ec="
  [mod."github.com/go-jose/go-jose/v3"]
    version = "v3.0.3"
    hash = "sha256-PsjN1vVhAFI6X11iIkpQU4i7Ax6FvkhXNxApeBa2BvA="
  [mod."github.com/go-kit/kit"]
    version = "v0.13.0"
    hash = "sha256-EncDzq0JVtY+NLlW5lD+nbVewNYTTrfzlOxI4PuwREw="
  [mod."github.com/go-kit/log"]
    version = "v0.2.1"
    hash = "sha256-puLJ+up45X2j9E3lXvBPKqHPKOA/sFAhfCqGxsITW/Y="
  [mod."github.com/go-logfmt/logfmt"]
    version = "v0.6.0"
    hash = "sha256-RtIG2qARd5sT10WQ7F3LR8YJhS8exs+KiuUiVf75bWg="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.1"
    hash = "sha256-WM4badoqxXlBmqCRrnmtNce63dLlr/FJav3BJSYHvaY="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-sql-driver/mysql"]
    version = "v1.8.1"
    hash = "sha256-Vp/au38P1tf1jNTBW34rdb5mly0cde5IIXu+EMjDDUY="
  [mod."github.com/go-task/slim-sprig"]
    version = "v0.0.0-20230315185526-52ccab3ef572"
    hash = "sha256-D6NjCQbcYC53NdwzyAm4i9M1OjTJIVu4EIt3AD/Vxfg="
  [mod."github.com/golang/glog"]
    version = "v1.2.0"
    hash = "sha256-eCWkUlsWbHSjsuTw8HcNpj3KxT+QPvW5SSIv88hAsxA="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.4"
    hash = "sha256-N3+Lv9lEZjrdOWdQhFj6Y3Iap4rVLEQeI8/eFFyAMZ0="
  [mod."github.com/golang/snappy"]
    version = "v0.0.4"
    hash = "sha256-Umx+5xHAQCN/Gi4HbtMhnDCSPFAXSsjVbXd8n5LhjAA="
  [mod."github.com/google/cel-go"]
    version = "v0.20.1"
    hash = "sha256-zSYMhzDovuKaVhTmLJunkMsNg2PmUBI3WWVWZYfrMt0="
  [mod."github.com/google/certificate-transparency-go"]
    version = "v1.1.8"
    hash = "sha256-IGDFpoJ4hoMLS5MMeKICIuL6CaI4TjjQx0MTFNBjCWY="
  [mod."github.com/google/go-tpm"]
    version = "v0.9.0"
    hash = "sha256-0UcVN7/v76aXHVr/0AtZWDjl085/S2ekVt3mTqs7Z98="
  [mod."github.com/google/go-tspi"]
    version = "v0.3.0"
    hash = "sha256-ngMkHaEDxzM9uhg9mZ2nP/EAu8N9fp5pTCTyIsQD5QA="
  [mod."github.com/google/pprof"]
    version = "v0.0.0-20240327155427-868f304927ed"
    hash = "sha256-jsk7AakxRfQSp2o8JOvr+pu9oKf332oZ7DrT54yaEyw="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.19.1"
    hash = "sha256-rCFj39yIjx/xX99OSAncloxaJP1IJG59fK2CwU5M2WY="
  [mod."github.com/huandu/xstrings"]
    version = "v1.4.0"
    hash = "sha256-lw0qFsUNW6ZPXNwawpUSfJQjZ+/PKMLkC/yW64t1yng="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.16"
    hash = "sha256-gh2TEAq8YrZOEAf6SFW4AIcEEUguD68G+7/VUnBeWwM="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jackc/chunkreader/v2"]
    version = "v2.0.1"
    hash = "sha256-LNAEmbsxWOVPtcQ1fE1JC1yTaqyvZGa/k4zocWFBRTo="
  [mod."github.com/jackc/pgconn"]
    version = "v1.14.3"
    hash = "sha256-eIOJvZeUikfpuNUQirE1ojLqPvWcH4LBr8katTKq+os="
  [mod."github.com/jackc/pgio"]
    version = "v1.0.0"
    hash = "sha256-4W0PGZlkbBZcSJmPyXi9v1gAJIK9ujVLlcbxEOx9J1A="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgproto3/v2"]
    version = "v2.3.3"
    hash = "sha256-51DRxujLI0GzqM2kD4L+iOye3KhoAoVOGAYVa/EKsq4="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20231201235250-de7065d80cb9"
    hash = "sha256-j3pc2r15nf6FmLS+oLeKKYlJSI8jClk5fBOgQbhLrNI="
  [mod."github.com/jackc/pgtype"]
    version = "v1.14.3"
    hash = "sha256-cZHgMsviRkSMUZck7i9/ewXG5wCVQBcdAC+f3JPtr+w="
  [mod."github.com/jackc/pgx/v4"]
    version = "v4.18.3"
    hash = "sha256-DSHYalGrmZ4+eHmglBSCCSfMomb/lBKusfXeOhnWjo0="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.7"
    hash = "sha256-UkW+tAFEZYj067z9gXDQjQx0dCF8noCn5OSw/APh4oo="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.2.7"
    hash = "sha256-bjinp7b7qWk+DcZDDv1EedJxZqGxp2NWY+NYKBfE5xU="
  [mod."github.com/libdns/libdns"]
    version = "v0.2.2"
    hash = "sha256-RaJz49yg14WVAxmmqvNfsL4PmQ16asg1rIipIKM3/QM="
  [mod."github.com/manifoldco/promptui"]
    version = "v0.9.0"
    hash = "sha256-Fe2OPoyRExZejwtUBivKhfJAJW7o9b1eyYpgDlWQ1No="
  [mod."github.com/mastercactapus/proxyprotocol"]
    version = "v0.0.4"
    hash = "sha256-7wUqy9EDfR9XM4FRQ5KoqiueGCujGRtGPHYMnI/2fW0="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mgutz/ansi"]
    version = "v0.0.0-20200706080929-d51e80ef957d"
    hash = "sha256-RY6deYqJKpTTttr5tH2VW+PtuUIcieEq3Y6fGqRL0vk="
  [mod."github.com/mholt/acmez"]
    version = "v1.2.0"
    hash = "sha256-zfj14WFQr1/AO64gYsbFk4a4T0dsMEs+W3uIa9968/M="
  [mod."github.com/miekg/dns"]
    version = "v1.1.58"
    hash = "sha256-UGvyC1Abh2S5VaAUCV9AUuDMrCvpiWQy/UnYM9DfIB8="
  [mod."github.com/mitchellh/copystructure"]
    version = "v1.2.0"
    hash = "sha256-VR9cPZvyW62IHXgmMw8ee+hBDThzd2vftgPksQYR/Mc="
  [mod."github.com/mitchellh/go-ps"]
    version = "v1.0.0"
    hash = "sha256-HzxVHNLHZpnsBuPcub0G+9jjDcDOsxM/6wifbsxf7EY="
  [mod."github.com/mitchellh/reflectwalk"]
    version = "v1.0.2"
    hash = "sha256-VX9DPqChm7jPnyrA3RAYgxAFrAhj7TRKIWD/qR9Zr9s="
  [mod."github.com/onsi/ginkgo/v2"]
    version = "v2.17.1"
    hash = "sha256-kZgSreUHuYwl6Hh1SHmSasBwbV7qeYeg4BFYoxMchg8="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.19.0"
    hash = "sha256-YV8sxMPR+xorTUCriTfcFsaV2b7PZfPJDQmOgUYOZJo="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.0"
    hash = "sha256-TAD0mm7msYHo99yoNijeYzlDD0i1Vg3uTetpkDUWQo8="
  [mod."github.com/prometheus/common"]
    version = "v0.51.1"
    hash = "sha256-f9wmQSuEjcXu8qPrXnwJa1FcBIVQDVtdBxWwpeUb5NA="
  [mod."github.com/prometheus/procfs"]
    version = "v0.13.0"
    hash = "sha256-J31K36TkIiQU2EGOcmqDa+dkoKXiVuxafPVT4rKbEsg="
  [mod."github.com/quic-go/qpack"]
    version = "v0.4.0"
    hash = "sha256-QWIumzmHD94DlNp9G3AQf9QCtF+Kv0pShT1+FH7/I/c="
  [mod."github.com/quic-go/quic-go"]
    version = "v0.42.0"
    hash = "sha256-yWH0UzgnZGl/RkoXFFek5jGJuo4LjVeLfutXQeWP/G8="
  [mod."github.com/rs/xid"]
    version = "v1.5.0"
    hash = "sha256-u0QLm2YFMJqEjUhpWcLwfoS9lNHUxc2A79MObsqVbVU="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/shopspring/decimal"]
    version = "v1.3.1"
    hash = "sha256-MA3RmMQKPrposbqXcHdvAJL50O1WsIe0EBd7rMSWPPA="
  [mod."github.com/shurcooL/sanitized_anchor_name"]
    version = "v1.0.0"
    hash = "sha256-DtFSzeLmD1fAl103ncgwab7Vv2F0aulsA+gbkq24ab8="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.3"
    hash = "sha256-EnxsWdEUPYid+aZ9H4/iMTs1XMvCLbXZRDyvj89Ebms="
  [mod."github.com/slackhq/nebula"]
    version = "v1.8.2"
    hash = "sha256-VPgny+E7etXH2fo5GfZPJR15SW1fY44zpaxPTVC49mc="
  [mod."github.com/smallstep/certificates"]
    version = "v0.26.0"
    hash = "sha256-JHKEzZvPhc6i0baBUjhTJ7NVceM5JwZstY4eagiHGVc="
  [mod."github.com/smallstep/go-attestation"]
    version = "v0.4.4-0.20240109183208-413678f90935"
    hash = "sha256-YoJ9bHIiUJ5JsSzJWYn7Qp7CjfMgzygnc6OBclmnqe0="
  [mod."github.com/smallstep/nosql"]
    version = "v0.6.0"
    hash = "sha256-cv+ZRZMWzmDSSzPQdWfvgfE0N1KVtuapYOKPeOzs/B0="
  [mod."github.com/smallstep/pkcs7"]
    version = "v0.0.0-20231107075624-be1870d87d13"
    hash = "sha256-Bznf1oytIlUBbNtEuZHPGlf0cCPRPPVO6wQZFIoXxxU="
  [mod."github.com/smallstep/scep"]
    version = "v0.0.0-20240214080410-892e41795b99"
    hash = "sha256-26qHV4ACaSWiandGxfRfrOc5iTTcqqpKF7c4czXkaP4="
  [mod."github.com/smallstep/truststore"]
    version = "v0.13.0"
    hash = "sha256-Hs8FALZepOnVbUpOg99zdlhMMKAoPDp/i9ADM97jlio="
  [mod."github.com/spf13/cast"]
    version = "v1.6.0"
    hash = "sha256-hxioqRZfXE0AE5099wmn3YG0AZF8Wda2EB4c7zHF6zI="
  [mod."github.com/spf13/cobra"]
    version = "v1.8.0"
    hash = "sha256-oAE+fEaRfZPE541IPWE0GMeBBYgH2DMhtZNxzp7DFlY="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stoewer/go-strcase"]
    version = "v1.3.0"
    hash = "sha256-X0ilcefeqVQ44B9WT6euCMcigs7oLFypOQaGI33kGr8="
  [mod."github.com/tailscale/tscert"]
    version = "v0.0.0-20230806124524-28a91b69a046"
    hash = "sha256-UAs5D5Se0TycAJr7D62/hdENEfoqYlvIgHZmS5yb938="
  [mod."github.com/urfave/cli"]
    version = "v1.22.14"
    hash = "sha256-lpNDP0bM02JWeUjCOXU8HwHk3FT5zB4gIOO/EvaxRao="
  [mod."github.com/x448/float16"]
    version = "v0.8.4"
    hash = "sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE="
  [mod."github.com/yuin/goldmark"]
    version = "v1.7.0"
    hash = "sha256-/R5M27JnsPh67xp+QBAFUbCV50/HOm2hcPhErja1PCc="
  [mod."github.com/yuin/goldmark-highlighting/v2"]
    version = "v2.0.0-20230729083705-37449abec8cc"
    hash = "sha256-HpiwU7jIeDUAg2zOpTIiviQir8dpRPuXYh2nqFFccpg="
  [mod."github.com/zeebo/blake3"]
    version = "v0.2.3"
    hash = "sha256-ZepnzkvOyicTGL078O1F84q0TzBAouJlB5AMmfsiOIg="
  [mod."go.etcd.io/bbolt"]
    version = "v1.3.9"
    hash = "sha256-98cKiMZcxl11laO3IiRHnhSgh7mEjl0iKlPxsSPdbww="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.49.0"
    hash = "sha256-1/7YxtXZM4i75rXXIO6UN4CTY93nE/v2k2htS0uUOVg="
  [mod."go.opentelemetry.io/contrib/propagators/autoprop"]
    version = "v0.49.0"
    hash = "sha256-0hKZ7v1yDkyLdnXNMd7QQtjkZdSEjBzKfqgVH+/IWsA="
  [mod."go.opentelemetry.io/contrib/propagators/aws"]
    version = "v1.24.0"
    hash = "sha256-ddt+wD5Hp9wpb8WuRtUHzp+SQMwi40goWhP2FkB8NDU="
  [mod."go.opentelemetry.io/contrib/propagators/b3"]
    version = "v1.24.0"
    hash = "sha256-kprGHslgM2fvgXa9OuGIeCO+418JC/C+yz6FR+qwTQg="
  [mod."go.opentelemetry.io/contrib/propagators/jaeger"]
    version = "v1.24.0"
    hash = "sha256-mL2JufzHXAHMaFChxlfUE5Sn7NUgcx9SgzWu8yqSS4Q="
  [mod."go.opentelemetry.io/contrib/propagators/ot"]
    version = "v1.24.0"
    hash = "sha256-pUHKmt2UdjekkU0ZZqJq+NwDBTzlOxWbQ8xFgEPmxME="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.24.0"
    hash = "sha256-VGyV7EqJX6mRY0Ecyg+g0IZy+dt1GES4r9txQcaTNUg="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.24.0"
    hash = "sha256-GDnz8hLiRH4Sdb7XLAAI5HlY4fFJ+v2nyj/KwNqgw6E="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"]
    version = "v1.24.0"
    hash = "sha256-knWmLjdXQWY4rHj2CJjlZCVU9MYzMay+3qnjs0h2tic="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.24.0"
    hash = "sha256-KB5UQiaVmbB2VZO3al4WHb5HY79ioWaAQjaGkUKLvP8="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.24.0"
    hash = "sha256-1OSoklX/oBMpoTWN9x6QRQCiNqaNW6spVnUQ1Jt+tyU="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.24.0"
    hash = "sha256-FHP0hg+i7+wxCsM0u/5hQcgvvr3D+lq8o/7E/HkaW4s="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.1.0"
    hash = "sha256-csIVBsq+qLFKujlcMGJuXHCu4258MTKPnjhjmDiP+1U="
  [mod."go.step.sm/cli-utils"]
    version = "v0.9.0"
    hash = "sha256-sa2i2/XOZFiX5U2q7sZBcP+e3oJdGjPjf34lUanCoT0="
  [mod."go.step.sm/crypto"]
    version = "v0.44.2"
    hash = "sha256-qZG046nMdyNqtyXZYPw+vOlQskvf2mctXFbOpZA96xo="
  [mod."go.step.sm/linkedca"]
    version = "v0.20.1"
    hash = "sha256-23JHcIa7rSnjTPQ5pS91ktRG+LdUI22HbZr9uK3ES24="
  [mod."go.uber.org/mock"]
    version = "v0.4.0"
    hash = "sha256-mJN2cPmAMTZQzOnTpJ8zi9QH2m3OAKI4IpnQW9QYS8s="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.27.0"
    hash = "sha256-8655KDrulc4Das3VRduO9MjCn8ZYD5WkULjCvruaYsU="
  [mod."golang.org/x/crypto"]
    version = "v0.21.0"
    hash = "sha256-Z4k1LvFh4Jai7HUe6TTuXSG3VnuiRpMwdARIdZZqSYk="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240325151524-a685a6edb6d8"
    hash = "sha256-bYUSDnC/XOij85mLaW3bWD+2xRxby7ezXOvaPJ2e0lQ="
  [mod."golang.org/x/mod"]
    version = "v0.16.0"
    hash = "sha256-aN1Cz5Wqd9YCjK8nFW6JWn+n1HfFoEcgYZmGO/FYtbw="
  [mod."golang.org/x/net"]
    version = "v0.22.0"
    hash = "sha256-pcefO4noO9I6mATKBWF6shgIjZvFg0kDsV1Jo/NsFns="
  [mod."golang.org/x/sync"]
    version = "v0.6.0"
    hash = "sha256-LLims/wjDZtIqlYCVHREewcUOX4hwRwplEuZKPOJ/HI="
  [mod."golang.org/x/sys"]
    version = "v0.18.0"
    hash = "sha256-bIFhfFp7Sj0E1gcE3X3l/jecCfSRLgrkb8f0Yr6tVR0="
  [mod."golang.org/x/term"]
    version = "v0.18.0"
    hash = "sha256-lpze9arFZIhBV8Ht3VZyoiUwqPkeH2IwfXt8M3xljiM="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
  [mod."golang.org/x/tools"]
    version = "v0.19.0"
    hash = "sha256-Xf05Ao398gBzxn5C8H6x+XsLjFLIm+UUfpDekQYA0cw="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20240325203815-454cdb8f5daa"
    hash = "sha256-i01yJ/HoOhfN2Ylc3mmzdoYN7430DSUFHnjy8M1ccAY="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20240325203815-454cdb8f5daa"
    hash = "sha256-P5SBku16dYnK4koUQxTeGwPxAAWH8rxbDm2pOzFLo/Q="
  [mod."google.golang.org/grpc"]
    version = "v1.62.1"
    hash = "sha256-1su6X0YT7MUflrTJijbq1CiisADZHudEx5sJq01TEaE="
  [mod."google.golang.org/protobuf"]
    version = "v1.33.0"
    hash = "sha256-cWwQjtUwSIEkAlAadrlxK1PYZXTRrV4NKzt7xDpJgIU="
  [mod."gopkg.in/natefinch/lumberjack.v2"]
    version = "v2.2.1"
    hash = "sha256-GaXWRDxhGy4Z4mgE+bJ8OE9SVvYUa9TnNiydnp2s1Ms="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."howett.net/plist"]
    version = "v1.0.1"
    hash = "sha256-aXTwU+4m3JBjdX81Tw6MM8u4d39aoUICwP0g2ersmb0="
